// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spooly.DAL.Ef;

#nullable disable

namespace Spooly.DAL.Migrations
{
    [DbContext(typeof(SpoolyDbContext))]
    [Migration("20260327231150_AddAppSettingsState")]
    partial class AddAppSettingsState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Spooly.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ElectricityPricePerKwhMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedCostPerPrintMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OperatingCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedPrinterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Spooly.Models.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Spooly.Models.FilamentMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountKg")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("AveragePricePerKgMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("EstimatedLengthMeters")
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("Spooly.Models.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePowerWatts")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("HourlyCostMoney")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Printers", (string)null);
                });

            modelBuilder.Entity("Spooly.Models.Transactions.TransactionBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Transactions", (string)null);

                    b.HasDiscriminator<string>("TransactionType").HasValue("TransactionBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Spooly.Models.Transactions.PrintTransaction", b =>
                {
                    b.HasBaseType("Spooly.Models.Transactions.TransactionBase");

                    b.Property<decimal>("ElectricityCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("ElectricityKwh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("EstimatedMetersUsed")
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal>("ExtraFixedCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FilamentKg")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FixedCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("PrintHours")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrinterNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrinterWearCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset?>("RevertedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RevertedByTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.ToTable("Transactions", t =>
                        {
                            t.Property("MaterialId")
                                .HasColumnName("PrintTransaction_MaterialId");

                            t.Property("MaterialNameSnapshot")
                                .HasColumnName("PrintTransaction_MaterialNameSnapshot");

                            t.Property("Note")
                                .HasColumnName("PrintTransaction_Note");
                        });

                    b.HasDiscriminator().HasValue("Print");
                });

            modelBuilder.Entity("Spooly.Models.Transactions.StockTransaction", b =>
                {
                    b.HasBaseType("Spooly.Models.Transactions.TransactionBase");

                    b.Property<decimal>("KgDelta")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaterialNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MetersDelta")
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
